# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  golang: cci-orb/golang@0.1.19
  win: circleci/windows@2.4.0

jobs:
  build_linux:
    machine:
      image: ubuntu-2004:202101-01
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  build_windows:
    executor:
      name: win/default
      shell: powershell.exe
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: systeminfo
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  build_docker:
    docker:
      - image: circleci/golang:1.16
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
    

workflows:
  version: 2
  build:
    jobs:
      - build_linux
      - build_windows